name: 'Setup node for the action'
description: 'Bump the npm version and push it on the repo'

inputs:
  version_type:
    description: 'Type of version bump (major, minor, patch)'
    required: true
    type: string
  MAINTAINER_NAME:
    description: 'The git user'
    required: true
    type: string
  MAINTAINER_EMAIL:
    description: 'The git mail'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Config git
      shell: bash
      run: |
        git config user.name '${{ inputs.MAINTAINER_NAME }}'
        git config user.email '${{ inputs.MAINTAINER_EMAIL }}'
    - name: Bump version
      shell: bash
      run: npm version ${{ inputs.version_type }}
    - name: Push version bump commit
      shell: bash
      run: |
        BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        git push origin HEAD:$BRANCH --follow-tags
