export enum ButtonThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT',
    DARK_BLUE = 'DARK_BLUE',
    LIGHT_BLUE = 'LIGHT_BLUE',
    DARK_DISABLED = 'DARK_DISABLED',
    LIGHT_DISABLED = 'LIGHT_DISABLED',
}
