export enum ClanReserveEnum {
    ADDITIONAL_BRIEFING = 'MILITARY_MANEUVERS',
    BATTLE_PAYMENTS = 'TACTICAL_TRAINING',
    TACTICAL_TRAINING = 'BATTLE_PAYMENTS',
    MILITARY_MANEUVERS = 'ADDITIONAL_BRIEFING',
}
