import { TankIconType } from './tank-icon.type';

export type IconsType =
    | 'castle'
    | 'map'
    | 'ok'
    | 'ko'
    | 'chargeur'
    | 'commandant'
    | 'opérateur_radio'
    | 'pilote_de_char'
    | 'tireur'
    | 'wrench'
    | 'pencil'
    | 'plus'
    | 'changelog'
    | 'information'
    | 'server'
    | 'visitor'
    | 'agreement'
    | 'redirect'
    | 'reserve'
    | 'userGroup'
    | 'waiting'
    | 'send'
    | TankIconType;
