openapi: 3.0.3
info:
  title: Wot API
  description: All api related to some World of tanks elements
  version: 1.0.2

servers:
  - url: https://fold-backend-5e6c2cf7c25c.herokuapp.com

paths:
  /api/private/v1/wot/news:
    get:
      tags:
        - wot-news
      description: Return the last wot news in the database
      operationId: wot-news
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WotsNews'
        500:
          description: Internal server error
      deprecated: false

components:
  schemas:
    WotsNews:
      title: WotNews
      description: The array of WotNew
      type: array
      items:
        $ref: '#/components/schemas/WotNews'
    WotNews:
      title: TankOverviewDto
      description: The overview of a tank
      type: object
      required:
        - title
        - url
        - image_url
        - tags
      properties:
        title:
          type: string
          description: The title of the news
          example: Sommet de l'arbre de juin 2024
          minLength: 1
        url:
          type: string
          description: The url of the new
          example: https://worldoftanks.eu/fr/news/general-news/halloween-2024-how-to-play/
          minLength: 23
        image_url:
          type: string
          description: The image url of the news
          example: https://eu-wotp.wgcdn.co/dcont/fb/image/1.26.1_1022x360_thumbnail.jpg
          minLength: 23
        tags:
          type: array
          description: The tags apply to the news
          example: ["sommet de l'arbre"]
          items:
            type: string
