# File: .github/workflows/ci.yml
name: Build and Test

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-build # This ensures only one job per branch
  cancel-in-progress: true # Cancels previous jobs in the group if a new job is triggered

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run stylelint
        run: npm run lint:scss
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test:ci

  build-and-test-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint:lib
      - name: Build the project
        run: npm run build:lib
      - name: Run tests
        run: npm run test:lib:ci
