on: [push]
name: Node
jobs:
    build:
        name: Check the application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.X'
            - name: Install
              run: npm ci --fund=false --audit=false
            - name: Check ESLint
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
